project:
  type: default
  output-dir: output/reports

execute:
  freeze: auto

bibliography: documentation/references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  apaquarto-docx:
    default: true
  apaquarto-html:
    default: true
